#!/usr/bin/env bash

tmp_file=/tmp/geimTests.proton-ge-custom.releases
log_file=geimLog_$(date '+%F_%T').log
debug_log=geimDebugLog_$(date '+%F_%T').log
notes_log=geimReleaseNotes_$(date '+%F_%T').log

rm -vf "$tmp_file" "$log_file" "$debug_log" "$notes_log"

##touch "$tmp_file" "$log_file" "$debug_log" "$notes_log" || exit 1

CleanUp() {
    rm -f "$tmp_file"
    unset GEIM_TESTS
}

trap 'CleanUp' EXIT

# Disable color escape codes in script stderr verbose output
export GEIM_TESTS=1

# Nuke previous state
NukePreviousState() {
    echo "Nuking previous state"
    rm -- *.log
    ge-install-manager -fXD
}

err_exit() {
    echo "error"
    exit 1
}

# Get a list of the available releases
# Parse ge-install-manager -L output into a tmp file
GetReleasesList() {
    while IFS= read -r; do
        REPLY=${REPLY%%[[:blank:]]*}
        REPLY=${REPLY//Proton-}
        printf '%s\n' "$REPLY" >> "$tmp_file"
    done < <(ge-install-manager -L)
}

InstallSmallRelease() {
    if ge-install-manager -zd "Proton-5.1-GE-1" 2>>"${debug_log}"; then
        if ge-install-manager -zi "Proton-5.1-GE-1" 2>>"${debug_log}"; then
            if ! ge-install-manager -zs "Proton-5.1-GE-1" 2>>"${debug_log}" 1>>"$log_file"; then
                err_exit
            fi
        else
            err_exit
        fi
    else
        err_exit
    fi
}

InstallAllReleases() {
    GetReleasesList
    while IFS= read -r; do
        [[ -z $REPLY ]] && continue
        ge-install-manager -zi "$REPLY" 2>>"$debug_log"
    done < "$tmp_file"
}

VerifyAll() {
    ge-install-manager -zV 2>>"${debug_log}"
}

# shellcheck disable=SC2129
[[ -f $tmp_file ]] && printf '%s\n%s\n\n' "Releases being checked:" "$(cat "$tmp_file")" >> "$log_file"
printf '%s\n%s\n\n' "Installed releases:" "$(ge-install-manager -l)" >> "$log_file"

GroupTests() {
    # List patch notes for each installed version
    while flag_installed=0 IFS= read -r || [[ -n $REPLY ]]; do
        [[ ${REPLY,,} == 'installed'* ]] && { flag_installed=1; continue; }
        [[ ${REPLY,,} == 'saved'* ]] && { flag_installed=0; continue; }
        ((flag_installed)) && {
            # Remove extra info
            REPLY=${REPLY//[[:blank:]]}
            REPLY=${REPLY%'('*}
            # Fix for 5.0-ge-1-no-mouse-coord
            REPLY=${REPLY//'5.0-GE-1'/'5.0-GE-1-no-mouse-coord'}
            if ge-install-manager -R "$REPLY"; then
                if ge-install-manager -r "$REPLY"; then
                    if ge-install-manager -i "$REPLY"; then
                        if ge-install-manager -v "$REPLY"; then
                            if ! ge-install-manager -n "$REPLY" | tee -a "$notes_log"; then
                                err_exit
                            fi
                        else
                            err_exit
                        fi
                    else
                        err_exit
                    fi
                else
                    err_exit
                fi
            else
                err_exit
            fi
        }
    done < <(ge-install-manager -l)

    ge-install-manager -S 1>>"$log_file"

    printf '\n' >> "$log_file"

    sync -- *.log

    echo "All tests completed"
}

[[ $1 = 'nuke' ]] && NukePreviousState
[[ $1 = 'full' ]] && InstallAllReleases
[[ -z $1 ]] && InstallSmallRelease

# Run GroupTests()
GroupTests
