#!/usr/bin/env bash

tmp_file=/tmp/geimTests.proton-ge-custom.releases
log_file=geimLog_$(date '+%F_%T').log
debug_log=geimDebugLog_$(date '+%F_%T').log
notes_log=geimReleaseNotes_$(date '+%F_%T').log

rm -vf "$tmp_file" "$log_file" "$debug_log" "$notes_log"

##touch "$tmp_file" "$log_file" "$debug_log" "$notes_log" || exit 1

CleanUp () {
    rm -f "$tmp_file"
    unset GEIM_TESTS
}

trap 'CleanUp' EXIT

# Disable color escape codes in script stderr verbose output
export GEIM_TESTS=1

##ge-install-manager -fD

# Log the output of ReportEnvironmentInfo()
ge-install-manager -fzZ 2>/dev/null |& tee -a "$log_file"

ge-install-manager -S |& tee -a "$log_file"

# Get a list of the available releases
# Parse ge-install-manager -L output into a tmp file
while IFS= read -r; do
    REPLY=${REPLY%%[[:blank:]]*}
    ##REPLY=${REPLY//Proton-}
    printf '%s\n' "$REPLY" >> "$tmp_file"
    ge-install-manager -zd "$REPLY" 2>>"$debug_log"
    ge-install-manager -zi "$REPLY" 2>>"$debug_log"
    ge-install-manager -zs "$REPLY" 2>>"$debug_log"
done < <(ge-install-manager -L)

# shellcheck disable=SC2129
printf '%s\n%s\n\n%s\n%s\n\n' \
       "Releases available:" "$(cat "$tmp_file")" \
       "Installed releases:" "$(ge-install-manager -l)" >> "$log_file"

GroupTests () {
    if ge-install-manager -zV 2>>"$debug_log"; then
        # List patch notes for each installed version
        while flag_installed=0 IFS= read -r; do
            [[ ${REPLY,,} == 'installed'* ]] && { flag_installed=1; continue; }
            [[ ${REPLY,,} == 'saved'* ]] && { flag_installed=0; continue; }
            ((flag_installed)) && {
                # Remove extra info
                REPLY=${REPLY//[[:blank:]]}
                REPLY=${REPLY%'('*}
                # Fix for 5.0-ge-1-no-mouse-coord
                REPLY=${REPLY//'5.0-GE-1'/'5.0-GE-1-no-mouse-coord'}
                ge-install-manager -n "$REPLY" | tee -a "$notes_log"
            }
        done < <(ge-install-manager -l |& tee -a "$log_file")

        printf '\n' >> "$log_file"

        echo "All tests completed"
    fi
}

GroupTests
