#!/usr/bin/env bash

if [[ -f ge-install-manager ]]; then
    [[ -w $PWD ]] || { echo "No write access to $PWD"; exit 1; }
    if ctags --language-force=Sh --sort=no --kinds-Sh='{function}' ge-install-manager; then
        echo "ctags returned success"
    else
        echo "ctags returned >0"
    fi
else
    echo "ge-install-manager not found"
fi
